# Generated by Django 5.2.2 on 2025-07-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="login",
            new_name="username",
        ),
    ]
