# Generated by Django 5.2.2 on 2025-07-09 07:02
from django.apps import apps as global_apps
from django.contrib.auth.management import create_permissions
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def create_default_groups(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    for app_config in global_apps.get_app_configs():
        create_permissions(app_config, verbosity=0)
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    CustomUser = apps.get_model("users", "CustomUser")

    user_ct = ContentType.objects.get_for_model(CustomUser)

    clients_group, _ = Group.objects.get_or_create(name="clients")
    admins_group, _ = Group.objects.get_or_create(name="admins")
    banned_group, _ = Group.objects.get_or_create(name="banned")

    for codename in ["add_customuser", "change_customuser", "delete_customuser", "view_customuser"]:
        perm = Permission.objects.get(codename=codename, content_type=user_ct)
        admins_group.permissions.add(perm)


def delete_groups(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["clients", "admins", "banned"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_customuser_balance"),
    ]

    operations = [
        migrations.RunPython(create_default_groups, delete_groups),
    ]
