[project]
name = "store"
version = "0.1.0"
description = ""
authors = [
    { name = "Bichurashka", email = "bichurash@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "django (>=5.2.3,<6.0.0)",
    "djangorestframework (>=3.16.0,<4.0.0)",
    "psycopg2 (>=2.9.10,<3.0.0)",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)",
    "pydantic (>=2.11.9,<3.0.0)",
    "celery (>=5.6.0,<6.0.0)",
    "redis (>=7.1.0,<8.0.0)",
    "django-celery-beat (>=2.8.1,<3.0.0)",
    "django-stubs[compatible-mypy] (>=5.2.9,<6.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
flake8 = "^7.3.0"
isort = "^6.0.1"
mypy = "^1.16.1"
coverage = "^7.9.1"
django-stubs = "^5.2.2"

[tool.coverage.run]
branch = true
omit = [
    "manage.py",
    "asgi.py",
    "wsgi.py",
    "settings.py",
    "*/migrations/*",
    "*/tests/*",
    "*/urls*",
]

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
namespace_packages = true
disallow_untyped_defs = true
check_untyped_defs = true
warn_redundant_casts = true
show_error_codes = true
ignore_missing_imports = true
warn_unused_configs = true
warn_return_any = true
warn_unreachable = true
exclude = ["manage.py"]

[tool.django-stubs]
django_settings_module = "mysite.settings"