# Generated by Django 5.2.2 on 2025-08-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_alter_items_category_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="parent_id",
            new_name="parent",
        ),
        migrations.RenameField(
            model_name="discounts",
            old_name="category_id",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="items",
            old_name="category_id",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="orderitems",
            old_name="item_id",
            new_name="item",
        ),
        migrations.RenameField(
            model_name="orderitems",
            old_name="order_id",
            new_name="order",
        ),
        migrations.RenameField(
            model_name="orders",
            old_name="user_id",
            new_name="user",
        ),
    ]
