# Generated by Django 5.2.2 on 2026-01-20 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_rename_parent_id_category_parent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="base_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderitems",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="items", to="goods.orders"
            ),
        ),
    ]
