# Generated by Django 5.2.2 on 2026-10-07 07:57

from django.db import migrations
from django.db.models import Count, DecimalField, ExpressionWrapper, F, Min, Sum


def cleanup_before_constraints(apps, schema_editor):  # type: ignore[no-untyped-def]
    """Remove data that would violate the new unique constraints and normalize discount types"""
    Orders = apps.get_model("goods", "Orders")
    OrderItems = apps.get_model("goods", "OrderItems")
    Discounts = apps.get_model("goods", "Discounts")

    # Several Pending orders per user: keep the oldest one, cancel the rest (data is kept)
    duplicated_users = (
        Orders.objects.filter(status="Pending")
        .values("user_id")
        .annotate(cnt=Count("id"), keep_id=Min("id"))
        .filter(cnt__gt=1)
    )
    for row in duplicated_users:
        Orders.objects.filter(user_id=row["user_id"], status="Pending").exclude(
            id=row["keep_id"]
        ).update(status="Canceled")

    # Several rows for the same (order, item): sum amounts into the oldest row, delete the rest
    affected_orders = set()
    duplicated_rows = (
        OrderItems.objects.values("order_id", "item_id")
        .annotate(cnt=Count("id"), keep_id=Min("id"), total=Sum("amount"))
        .filter(cnt__gt=1)
    )
    for row in duplicated_rows:
        OrderItems.objects.filter(id=row["keep_id"]).update(amount=row["total"])
        OrderItems.objects.filter(order_id=row["order_id"], item_id=row["item_id"]).exclude(
            id=row["keep_id"]
        ).delete()
        affected_orders.add(row["order_id"])

    # Signals don't run inside migrations, so recalculate prices of merged orders here
    for order_id in affected_orders:
        total = OrderItems.objects.filter(order_id=order_id).aggregate(
            total=Sum(
                ExpressionWrapper(F("item__price") * F("amount"), output_field=DecimalField())
            )
        )["total"]
        Orders.objects.filter(id=order_id).update(price=total or 0)

    # Discount types must match model choices ("Fixed" / "Percentage")
    Discounts.objects.filter(type__iexact="fixed").update(type="Fixed")
    Discounts.objects.filter(type__iexact="percentage").update(type="Percentage")


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_items_base_price_alter_orderitems_order"),
    ]

    operations = [
        migrations.RunPython(cleanup_before_constraints, migrations.RunPython.noop),
    ]
