# Generated by Django 5.2.2 on 2026-10-07 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_cleanup_before_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="discounts",
            index=models.Index(
                fields=["start_datetime", "end_datetime"], name="discounts_period_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="orders",
            index=models.Index(fields=["user", "status"], name="orders_user_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="orderitems",
            constraint=models.UniqueConstraint(
                fields=("order", "item"), name="orderitems_unique_order_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="orders",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "Pending")),
                fields=("user",),
                name="orders_one_pending_per_user",
            ),
        ),
    ]
